const State = {
  States: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'New Delhi',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Telangana',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ],
  Quota: ['os', 'ai'],
  DegreeType: [
    'bachelor of engineering',
    'bachelor of engineering and Technology',
  ],
  Institute: [
    'National Institute of Technology',
    'Indian Institute of Technology',
  ],
  Program: [
    'Artificial Intelligence',
    'Electronics and Communication Engineering',
    'Computer Science and Engineering',
    'Mecanical Engineering',
    'Civil Engineering',
    'Bio Technology',
    'Camical Engineering',
    'Architecture',
  ],
};

export default State;
