// import card1 from "./img/card1.png";
// import card2 from "./img/card2.png";
// import card3 from "./img/card3.png";

// export const CardData = [
//   {
//     stickyColor: "#27AE60",
//     title: "Tri-Mastery Plan",
//     priceStrike: "₹1399",
//     price: "₹1399",
//     priceColor: "#240642",
//     sessions: "For 4 Sessions",
//     sessionColor: "#252525",
//     description: [
//       "Short term focus with affordable pricing.",
//       "Comprehensive 4-session plan providing balanced, personalized academic support",
//       "Personalized Study Plan",
//       "Cost per session: ₹350",
//       "Additional sessions available at ₹325 each within the plan",
//     ],
//     textColor: "rgba(2, 13, 43, 0.74)",
//     headercolor: "#4E18CD",
//     img: card1,
//     button: "Get Started",
//     btncolor: "#4E18CD",
//     btntextcolor: "#FFF",
//     backgroundColor: "#E7E7E7",
//     savings: "Potential Savings: ₹0 (0%)",
//   },
//   {
//     stickyColor: "#FFD700",
//     title: "Semester Boost",
//     priceStrike: "₹4197",
//     price: "₹3499",
//     priceColor: "#FFF",
//     sessions: "For 12 Sessions",
//     sessionColor: "#A2A2A2",
//     description: [
//       "Ideal for mid-term preparation and skill enhancement",
//       "12 sessions over 3 months",
//       "Personalized Study Plan",
//       "Cost per session: ₹292",
//       "Additional sessions available at ₹275 each within the plan",
//     ],
//     headercolor: "#A2A2A2",
//     img: card2,
//     textColor: "#E7E7E7",
//     button: "Get Started",
//     btntextcolor: "#4E18CD",
//     btncolor: "#FFF",
//     backgroundColor: "#4E18CD",
//     color: "#000",
//     savings: "Potential Savings: ₹698 (20%)",
//   },
//   {
//     stickyColor: "#27AE60",
//     title: "Year-Long Mastery",
//     priceStrike: "₹8794",
//     price: "₹5999",
//     priceColor: "#240642",
//     sessions: "For 24 Sessions",
//     sessionColor: "#252525",
//     description: [
//       "Comprehensive support over 6 months",
//       "24 sessions for in-depth guidance and development",
//       "Personalized Study Plan",
//       "Lowest cost per session at ₹250",
//       "Additional sessions available at ₹250 each within the plan",
//     ],
//     headercolor: "#4E18CD",
//     img: card3,
//     textColor: "rgba(2, 13, 43, 0.74)",
//     button: "Get Started",
//     btntextcolor: "#FFF",
//     btncolor: "#4E18CD",
//     backgroundColor: "#E7E7E7",
//     color: "#000",
//     savings: "Potential Savings: ₹2395 (40%)",
//   },
// ];

// import card1 from "./img/card1.png";
// import card2 from "./img/card2.png";
// import card3 from "./img/card3.png";
import React from 'react';
import { PiAirplaneTakeoff } from 'react-icons/pi';
import { HiOutlineBolt } from 'react-icons/hi2';
import { HiOutlineDocumentPlus } from 'react-icons/hi2';

export const CardData = [
  {
    stickyColor: '#27AE60',
    title: 'Steady Progress',
    priceStrike: '',
    price: '',
    priceColor: '#240642',
    sessions: '',
    sessionColor: '#252525',
    description: [],
    textColor: 'rgba(2, 13, 43, 0.74)',
    headercolor: '#4E18CD',
    icon: <HiOutlineBolt />,
    iconBackground: '#EAE8FF',
    priceStrikeThroughColor: '#747474',
    discountColor: '#757575',
    button: 'Get Started',
    btncolor: '#4E18CD',
    btntextcolor: '#FFF',
    backgroundColor: '#FFFFFF',
    savings: 'Potential Savings: ₹0 (0%)', // Will be calculated based on backend data
  },
  {
    stickyColor: '#FFD700',
    title: 'Tri-Mastery',

    priceStrike: '',
    price: '',
    priceColor: '#FFF',
    sessions: '',
    sessionColor: '#A2A2A2',
    description: [],
    headercolor: '#FFFFFF',
    icon: <PiAirplaneTakeoff />,
    iconBackground: '#FFFFFF',
    priceStrikeThroughColor: '#E5F5FF',
    discountColor: '#E5F5FF',
    textColor: '#E7E7E7',
    button: 'Get Started',
    btntextcolor: '#4E18CD',
    btncolor: '#FFF',
    backgroundColor: '#4E18CD',
    color: '#000',
    savings: 'Potential Savings: ₹698 (20%)',
  },
  {
    stickyColor: '#27AE60',
    title: 'Semester Boost',
    priceStrike: '',
    price: '',
    priceColor: '#240642',
    sessions: '',
    sessionColor: '#252525',
    description: [],
    headercolor: '#4E18CD',
    icon: <HiOutlineDocumentPlus />,
    iconBackground: '#EAE8FF',
    priceStrikeThroughColor: '#747474',
    discountColor: '#757575',
    textColor: 'rgba(2, 13, 43, 0.74)',
    button: 'Get Started',
    btntextcolor: '#FFF',
    btncolor: '#4E18CD',
    backgroundColor: '#FFFFFF',
    color: '#000',
    savings: 'Potential Savings: ₹2395 (60%)',
  },
];
